/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ButtonGroup;

import javax.swing.JOptionPane;
import control.KendaraanControl;
import exception.InputIdException;
import exception.JenisKendaraanException;
import javax.swing.JOptionPane;
import model.Kendaraan;
/**
 *
 * @author riksi
 */
public class KendaraanView extends javax.swing.JFrame {
    private KendaraanControl kendaraanControl;
    String action=null;
    
    public KendaraanView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        kendaraanControl = new KendaraanControl();
        
    }
    
    public void showKendaraan(){
        if()
        showDataTextArea.setText(dosenControl.showDataDosen());
    }
    
    public void setComponent(boolean value){
        inputID.setEnabled(value);
        inputNama.setEnabled(value);
        inputTahun.setEnabled(value);
        inputNo.setEnabled(value);
        
        inputJumlah.setEnabled(value);
        inputJenis.setEnabled(value);
        
        btnSave.setEnabled(value);
        btnCancel.setEnabled(value);
        
        jenisDosen.setEnabled(value);
        jenisStaff.setEnabled(value);
        
    }
    
    public void setEditDeleteBtn(boolean value){
        btnEdit.setEnabled(value);
        btnDelete.setEnabled(value);
    }
    
    public void clearText(){
        inputID.setText("");
        inputNama.setText("");
        inputTahun.setText("");
        inputNo.setText("");
        
        inputJumlah.setText("");
        inputJenis.setText("");
        
        jenisGroup.clearSelection();
    }
    
    
    //Exception belum dibuat

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisGroup = new javax.swing.ButtonGroup();
        panelHeader = new javax.swing.JPanel();
        labelKelompok = new javax.swing.JLabel();
        npmRiksi = new javax.swing.JLabel();
        npmPanji = new javax.swing.JLabel();
        labelOP1 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        panelButton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        panelInput = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        labelTahun = new javax.swing.JLabel();
        inputTahun = new javax.swing.JTextField();
        labelNo = new javax.swing.JLabel();
        inputNo = new javax.swing.JTextField();
        panelJenis = new javax.swing.JPanel();
        jenisDosen = new javax.swing.JRadioButton();
        jenisStaff = new javax.swing.JRadioButton();
        labelJumlah = new javax.swing.JLabel();
        inputJumlah = new javax.swing.JTextField();
        labelJenis = new javax.swing.JLabel();
        inputJenis = new javax.swing.JTextField();
        panelSaveCancel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        panelMobil = new javax.swing.JPanel();
        labelMobil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMobil = new javax.swing.JTextArea();
        panelMotor = new javax.swing.JPanel();
        labelMotor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaMotor = new javax.swing.JTextArea();
        labelRental = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(50, 50, 58));

        labelKelompok.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelKelompok.setForeground(new java.awt.Color(255, 255, 255));
        labelKelompok.setText("Kelompok 7");

        npmRiksi.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        npmRiksi.setForeground(new java.awt.Color(255, 255, 255));
        npmRiksi.setText("210711396");

        npmPanji.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        npmPanji.setForeground(new java.awt.Color(255, 255, 255));
        npmPanji.setText("210711397");

        labelOP1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        labelOP1.setForeground(new java.awt.Color(255, 255, 255));
        labelOP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOP1.setText("Object Persistence 1");

        panelContent.setBackground(new java.awt.Color(80, 80, 92));
        panelContent.setForeground(new java.awt.Color(255, 255, 255));

        panelButton.setBackground(new java.awt.Color(80, 80, 92));

        btnAdd.setBackground(new java.awt.Color(80, 80, 96));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(80, 80, 96));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(80, 80, 96));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        inputSearch.setBackground(new java.awt.Color(80, 80, 96));
        inputSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inputSearch.setForeground(new java.awt.Color(255, 255, 255));
        inputSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSearchActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(80, 80, 96));
        btnSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelInput.setBackground(new java.awt.Color(80, 80, 92));
        panelInput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        labelID.setForeground(new java.awt.Color(255, 255, 255));
        labelID.setText("ID Kendaraan");

        inputID.setBackground(new java.awt.Color(80, 80, 96));
        inputID.setForeground(new java.awt.Color(255, 255, 255));
        inputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDActionPerformed(evt);
            }
        });

        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Nama Kendaraan");

        inputNama.setBackground(new java.awt.Color(80, 80, 96));
        inputNama.setForeground(new java.awt.Color(255, 255, 255));

        labelTahun.setForeground(new java.awt.Color(255, 255, 255));
        labelTahun.setText("Tahun Pembuatan");

        inputTahun.setBackground(new java.awt.Color(80, 80, 96));
        inputTahun.setForeground(new java.awt.Color(255, 255, 255));

        labelNo.setForeground(new java.awt.Color(255, 255, 255));
        labelNo.setText("Nomor Plat");

        inputNo.setBackground(new java.awt.Color(80, 80, 96));
        inputNo.setForeground(new java.awt.Color(255, 255, 255));
        inputNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addComponent(inputID)
                    .addComponent(inputNama)
                    .addComponent(inputTahun)
                    .addComponent(inputNo)))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelTahun)
                .addGap(10, 10, 10)
                .addComponent(inputTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelTahun.getAccessibleContext().setAccessibleName("");

        panelJenis.setBackground(new java.awt.Color(80, 80, 92));
        panelJenis.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jenisGroup.add(jenisDosen);
        jenisDosen.setForeground(new java.awt.Color(255, 255, 255));
        jenisDosen.setText("Mobil");
        jenisDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisDosenActionPerformed(evt);
            }
        });

        jenisGroup.add(jenisStaff);
        jenisStaff.setForeground(new java.awt.Color(255, 255, 255));
        jenisStaff.setText("Motor");
        jenisStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisStaffActionPerformed(evt);
            }
        });

        labelJumlah.setForeground(new java.awt.Color(255, 255, 255));
        labelJumlah.setText("Jumlah Penumpang");

        inputJumlah.setBackground(new java.awt.Color(80, 80, 96));
        inputJumlah.setForeground(new java.awt.Color(255, 255, 255));
        inputJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJumlahActionPerformed(evt);
            }
        });

        labelJenis.setForeground(new java.awt.Color(255, 255, 255));
        labelJenis.setText("Jenis Tak");

        inputJenis.setBackground(new java.awt.Color(80, 80, 96));
        inputJenis.setForeground(new java.awt.Color(255, 255, 255));
        inputJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJenisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelJenisLayout = new javax.swing.GroupLayout(panelJenis);
        panelJenis.setLayout(panelJenisLayout);
        panelJenisLayout.setHorizontalGroup(
            panelJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJenisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jenisDosen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(inputJumlah)
                        .addComponent(labelJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelJumlah))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        panelJenisLayout.setVerticalGroup(
            panelJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJenisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisDosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelJumlah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jenisStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelJenis)
                .addGap(8, 8, 8)
                .addComponent(inputJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jenisDosen.getAccessibleContext().setAccessibleName("");
        jenisStaff.getAccessibleContext().setAccessibleName("");

        panelSaveCancel.setBackground(new java.awt.Color(80, 80, 92));

        btnSave.setBackground(new java.awt.Color(80, 80, 96));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(80, 80, 96));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSaveCancelLayout = new javax.swing.GroupLayout(panelSaveCancel);
        panelSaveCancel.setLayout(panelSaveCancelLayout);
        panelSaveCancelLayout.setHorizontalGroup(
            panelSaveCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaveCancelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelSaveCancelLayout.setVerticalGroup(
            panelSaveCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaveCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSaveCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMobil.setBackground(new java.awt.Color(80, 80, 92));

        labelMobil.setForeground(new java.awt.Color(255, 255, 255));
        labelMobil.setText("Data Mobil");

        areaMobil.setEditable(false);
        areaMobil.setBackground(new java.awt.Color(80, 80, 96));
        areaMobil.setColumns(20);
        areaMobil.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        areaMobil.setForeground(new java.awt.Color(255, 255, 255));
        areaMobil.setRows(5);
        jScrollPane1.setViewportView(areaMobil);

        javax.swing.GroupLayout panelMobilLayout = new javax.swing.GroupLayout(panelMobil);
        panelMobil.setLayout(panelMobilLayout);
        panelMobilLayout.setHorizontalGroup(
            panelMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMobilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMobilLayout.createSequentialGroup()
                        .addComponent(labelMobil)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMobilLayout.setVerticalGroup(
            panelMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMobilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMobil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMotor.setBackground(new java.awt.Color(80, 80, 92));

        labelMotor.setForeground(new java.awt.Color(255, 255, 255));
        labelMotor.setText("Data Motor");

        areaMotor.setEditable(false);
        areaMotor.setBackground(new java.awt.Color(80, 80, 96));
        areaMotor.setColumns(20);
        areaMotor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        areaMotor.setForeground(new java.awt.Color(255, 255, 255));
        areaMotor.setRows(5);
        jScrollPane2.setViewportView(areaMotor);

        javax.swing.GroupLayout panelMotorLayout = new javax.swing.GroupLayout(panelMotor);
        panelMotor.setLayout(panelMotorLayout);
        panelMotorLayout.setHorizontalGroup(
            panelMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMotor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMotorLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMotorLayout.setVerticalGroup(
            panelMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMotor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelContentLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(panelJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContentLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelSaveCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addComponent(panelMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addComponent(panelJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(panelSaveCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        labelRental.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelRental.setForeground(new java.awt.Color(255, 255, 255));
        labelRental.setText("Rental Kendaraan Negara");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelKelompok)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(npmPanji)
                            .addComponent(npmRiksi))))
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(labelRental))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(labelOP1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(labelKelompok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(npmRiksi))
                    .addComponent(labelOP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npmPanji)
                    .addComponent(labelRental))
                .addGap(18, 18, 18)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        setComponent(true);
        clearText();
        action = "Add";
    }//GEN-LAST:event_btnAddActionPerformed

    private void inputJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJumlahActionPerformed

    private void inputJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJenisActionPerformed

    private void inputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        setEditDeleteBtn(true);
        setComponent(false);
        
       try {
            //Dosen dosen = dosenControl.searchDosen(inputSearch.getText());
            if(!true){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan","Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                inputID.setText("ID-Motor");
                inputNama.setText("Ini Nama Motor");
                inputTahun.setText("2023");
                inputNo.setText("08123456789");
                
                inputJumlah.setText("10");
                inputJenis.setText("2 Tak");
                jenisDosen.setSelected(true);
            }
        } catch (Exception e) {
            System.out.println("Error "+e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void inputNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNoActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       setComponent(true);
       inputID.setEnabled(false);
        action = "Edit";
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?","Konfirmasi", JOptionPane.YES_NO_OPTION);
       if(getAnswer == JOptionPane.YES_OPTION){
            try {
                //dosenControl.deleteDataDosen(nidInput.getText());
                clearText();
                //showDosen();
                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus!");
            } catch (Exception e) {
                System.out.println("Error : "+e.getMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Data tidak jadi dihapus!");
        }
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void inputSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchActionPerformed

    private void jenisDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisDosenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       try{
//                inputKosongException();
//                noIndukDosenException();
//                tooManyInputException();
    
//                Dosen d = new Dosen(nidInput.getText(), namaInput.getText(),
//                      emailInput.getText(), handphoneInput.getText());
                if(action.equals("Add")){
//                    dosenControl.insertDataDosen(d);
                        JOptionPane.showMessageDialog(this, "Berhasil Tambah Data");
                }else{
//                    dosenControl.updateDataDosen(d, nidInput.getText());
                        JOptionPane.showMessageDialog(this, "Berhasil Edit Data");
                }
                clearText();
                setComponent(false);
                setEditDeleteBtn(false);
//                showDosen();
//            }catch(InputKosongException e){
//                JOptionPane.showMessageDialog(this, e.message());
//            }catch(NoIndukDosenException e){
//                JOptionPane.showMessageDialog(this, e.message());
//            }catch(TooManyInputException e){
//                JOptionPane.showMessageDialog(this, e.message());
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.toString());
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jenisStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KendaraanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KendaraanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KendaraanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KendaraanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KendaraanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMobil;
    private javax.swing.JTextArea areaMotor;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputJenis;
    private javax.swing.JTextField inputJumlah;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNo;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JTextField inputTahun;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jenisDosen;
    private javax.swing.ButtonGroup jenisGroup;
    private javax.swing.JRadioButton jenisStaff;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelJenis;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKelompok;
    private javax.swing.JLabel labelMobil;
    private javax.swing.JLabel labelMotor;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNo;
    private javax.swing.JLabel labelOP1;
    private javax.swing.JLabel labelRental;
    private javax.swing.JLabel labelTahun;
    private javax.swing.JLabel npmPanji;
    private javax.swing.JLabel npmRiksi;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelJenis;
    private javax.swing.JPanel panelMobil;
    private javax.swing.JPanel panelMotor;
    private javax.swing.JPanel panelSaveCancel;
    // End of variables declaration//GEN-END:variables
}
