/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.*;
import exception.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.*;
import table.*;

public class PenyewaanView extends javax.swing.JFrame {

    private KendaraanControl kControl;
    private CustomerControl cControl;
    private PenyewaanControl pControl;
    int selectedId = 0;
    String action = null;
    List<Customer> listCustomer;
    List<Kendaraan> listKendaraan;
    public PenyewaanView() {
        kControl=new KendaraanControl();
        cControl=new CustomerControl();
        pControl=new PenyewaanControl();
        initComponents();
        setComponents(false);
        setEditDeleteBtn(false);
        setKendaraanDropDown();
        setNamaDropDown();
        showPenyewaan();
    }
    
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    public void setComponents(boolean value){
        kendaraanDropDown.setEnabled(value);
        namaDropDown.setEnabled(value);
        
        lamaSewaInput.setEnabled(value);
        totalHargaInput.setEnabled(value);
        
        snackCheckBox.setEnabled(value);
        maskerCheckBox.setEnabled(value);
        tissueCheckBox.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
        
    }

    public void clearText(){
        kendaraanDropDown.setSelectedItem(ABORT);
        namaDropDown.setSelectedItem(ABORT);
        lamaSewaInput.setText("");
        totalHargaInput.setText("");
        snackCheckBox.setSelected(false);
        maskerCheckBox.setSelected(false);
        tissueCheckBox.setSelected(false);
    }
    
    
    public void setKendaraanDropDown(){
        listKendaraan=kControl.showAllKendaraan();
        for(int i=0;i<listKendaraan.size();i++){
            kendaraanDropDown.addItem(listKendaraan.get(i));
        }
    }
    public void setNamaDropDown(){
        listCustomer=cControl.showCustomer();
        for(int i=0;i<listCustomer.size();i++){
            namaDropDown.addItem(listCustomer.get(i));
        }
    }
    public void showPenyewaan(){
        penyewaanTable.setModel(pControl.showPenyewaan(""));
    }
    public void InputKosongException() throws InputKosongException{
        if (lamaSewaInput.getText().isEmpty() || totalHargaInput.getText().isEmpty() || 
                kendaraanDropDown.getSelectedIndex() == -1 || namaDropDown.getSelectedIndex() == -1) {
            throw new InputKosongException();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        exitPanel = new javax.swing.JPanel();
        iconShutdown = new javax.swing.JLabel();
        identityPanel = new javax.swing.JPanel();
        npm2 = new javax.swing.JLabel();
        npm1 = new javax.swing.JLabel();
        kelompokLabel = new javax.swing.JLabel();
        viewLabel = new javax.swing.JLabel();
        rentPanel = new javax.swing.JPanel();
        rentLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        vehiclePanel = new javax.swing.JPanel();
        vehicleLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerPanel = new javax.swing.JPanel();
        customerLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        penyewaanTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        fasilitasLabel = new javax.swing.JLabel();
        snackCheckBox = new javax.swing.JCheckBox();
        maskerCheckBox = new javax.swing.JCheckBox();
        tissueCheckBox = new javax.swing.JCheckBox();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        kendaraanDropDown = new javax.swing.JComboBox<>();
        namaDropDown = new javax.swing.JComboBox<>();
        lamaSewaInput = new javax.swing.JTextField();
        totalHargaInput = new javax.swing.JTextField();
        kendaraanLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        lamaSewaLabel = new javax.swing.JLabel();
        totalHargaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 204, 102));

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 204));

        exitPanel.setBackground(new java.awt.Color(255, 158, 14));
        exitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPanelMouseClicked(evt);
            }
        });

        iconShutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-shutdown-64 (1).png"))); // NOI18N

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(iconShutdown)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(iconShutdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        identityPanel.setBackground(new java.awt.Color(255, 255, 153));

        npm2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        npm2.setForeground(new java.awt.Color(51, 51, 51));
        npm2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        npm2.setText("210711397");

        npm1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        npm1.setForeground(new java.awt.Color(51, 51, 51));
        npm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        npm1.setText("210711396");

        kelompokLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        kelompokLabel.setForeground(new java.awt.Color(51, 51, 51));
        kelompokLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kelompokLabel.setText("Kelompok 7");

        viewLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 22)); // NOI18N
        viewLabel.setForeground(new java.awt.Color(51, 51, 51));
        viewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewLabel.setText("Vehicle Rental");

        javax.swing.GroupLayout identityPanelLayout = new javax.swing.GroupLayout(identityPanel);
        identityPanel.setLayout(identityPanelLayout);
        identityPanelLayout.setHorizontalGroup(
            identityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(identityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(identityPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(kelompokLabel))
                    .addComponent(viewLabel)
                    .addGroup(identityPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(identityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(npm2)
                            .addComponent(npm1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        identityPanelLayout.setVerticalGroup(
            identityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kelompokLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(npm1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(npm2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        rentPanel.setBackground(new java.awt.Color(255, 204, 102));

        rentLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        rentLabel.setForeground(new java.awt.Color(51, 51, 51));
        rentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rentLabel.setText("Vehicle Rental");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-rent-64.png"))); // NOI18N

        javax.swing.GroupLayout rentPanelLayout = new javax.swing.GroupLayout(rentPanel);
        rentPanel.setLayout(rentPanelLayout);
        rentPanelLayout.setHorizontalGroup(
            rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rentPanelLayout.setVerticalGroup(
            rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        vehiclePanel.setBackground(new java.awt.Color(255, 255, 204));
        vehiclePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehiclePanelMouseClicked(evt);
            }
        });

        vehicleLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        vehicleLabel.setForeground(new java.awt.Color(51, 51, 51));
        vehicleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicleLabel.setText("Vehicle");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/car (3).png"))); // NOI18N

        javax.swing.GroupLayout vehiclePanelLayout = new javax.swing.GroupLayout(vehiclePanel);
        vehiclePanel.setLayout(vehiclePanelLayout);
        vehiclePanelLayout.setHorizontalGroup(
            vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiclePanelLayout.createSequentialGroup()
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(vehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vehiclePanelLayout.setVerticalGroup(
            vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiclePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehicleLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        customerPanel.setBackground(new java.awt.Color(255, 255, 204));

        customerLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(51, 51, 51));
        customerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerLabel.setText("Customer");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-customer-64.png"))); // NOI18N

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(identityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vehiclePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addComponent(identityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehiclePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(rentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        penyewaanTable.setBackground(new java.awt.Color(255, 255, 204));
        penyewaanTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        penyewaanTable.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        penyewaanTable.setForeground(new java.awt.Color(0, 0, 0));
        penyewaanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        penyewaanTable.setAlignmentX(0.9F);
        penyewaanTable.setAlignmentY(0.9F);
        penyewaanTable.setRowHeight(30);
        penyewaanTable.setRowMargin(1);
        penyewaanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penyewaanTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(penyewaanTable);

        jPanel1.setBackground(new java.awt.Color(255, 210, 122));

        addBtn.setBackground(new java.awt.Color(102, 255, 102));
        addBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 0, 0));
        addBtn.setText("Tambah");
        addBtn.setBorder(null);
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(255, 204, 51));
        editBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(0, 0, 0));
        editBtn.setText("Ubah");
        editBtn.setBorder(null);
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 91, 91));
        deleteBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn.setText("Hapus");
        deleteBtn.setBorder(null);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(153, 204, 255));
        searchBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(51, 51, 51));
        searchBtn.setText("Cari");
        searchBtn.setBorder(null);
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchInput.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        fasilitasLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        fasilitasLabel.setForeground(new java.awt.Color(51, 51, 51));
        fasilitasLabel.setText("Fasilitas");

        snackCheckBox.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        snackCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        snackCheckBox.setText("Snack");
        snackCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snackCheckBoxActionPerformed(evt);
            }
        });

        maskerCheckBox.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maskerCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        maskerCheckBox.setText("Masker");

        tissueCheckBox.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tissueCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        tissueCheckBox.setText("Tissue");
        tissueCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tissueCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fasilitasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(snackCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tissueCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(maskerCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fasilitasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snackCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maskerCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tissueCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveBtn.setBackground(new java.awt.Color(0, 204, 102));
        saveBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(51, 51, 51));
        saveBtn.setText("Save");
        saveBtn.setBorder(null);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(51, 255, 255));
        cancelBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(0, 0, 0));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(null);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));

        kendaraanDropDown.setBackground(new java.awt.Color(255, 255, 204));
        kendaraanDropDown.setForeground(new java.awt.Color(51, 51, 51));
        kendaraanDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kendaraanDropDownActionPerformed(evt);
            }
        });

        namaDropDown.setBackground(new java.awt.Color(255, 255, 204));
        namaDropDown.setForeground(new java.awt.Color(51, 51, 51));

        lamaSewaInput.setBackground(new java.awt.Color(255, 255, 204));
        lamaSewaInput.setForeground(new java.awt.Color(51, 51, 51));
        lamaSewaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaSewaInputActionPerformed(evt);
            }
        });

        totalHargaInput.setBackground(new java.awt.Color(255, 255, 204));
        totalHargaInput.setForeground(new java.awt.Color(51, 51, 51));
        totalHargaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaInputActionPerformed(evt);
            }
        });

        kendaraanLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        kendaraanLabel.setForeground(new java.awt.Color(51, 51, 51));
        kendaraanLabel.setText("Kendaraan");

        namaLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(51, 51, 51));
        namaLabel.setText("Nama Customer");

        lamaSewaLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lamaSewaLabel.setForeground(new java.awt.Color(51, 51, 51));
        lamaSewaLabel.setText("Lama Sewa");

        totalHargaLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        totalHargaLabel.setForeground(new java.awt.Color(51, 51, 51));
        totalHargaLabel.setText("Total Harga");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kendaraanDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLabel)
                    .addComponent(kendaraanLabel))
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lamaSewaLabel)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lamaSewaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addComponent(totalHargaInput))
                    .addComponent(totalHargaLabel))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kendaraanLabel)
                    .addComponent(lamaSewaLabel))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lamaSewaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kendaraanDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalHargaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaDropDown)
                    .addComponent(totalHargaInput))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18))))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponents(true);
        action="Tambah";
        searchInput.setText("");
        clearText();
    }//GEN-LAST:event_addBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        clearText();
        setComponents(false);
        setEditDeleteBtn(false);
        showPenyewaan();
        searchInput.setText("");
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            InputKosongException();
            
            String fasilitas;
            int selectedKendaraan = kendaraanDropDown.getSelectedIndex();
            int selectedCustomer = namaDropDown.getSelectedIndex();
            
            Kendaraan kendaraan = listKendaraan.get(selectedKendaraan);
            Customer customer = listCustomer.get(selectedCustomer);
            
            if (snackCheckBox.isSelected()) fasilitas = "Snack, ";
            else fasilitas = "-, ";
            
            if (maskerCheckBox.isSelected()) fasilitas = fasilitas.concat("Masker, ");
            else fasilitas = fasilitas.concat("-, ");
            
            if (tissueCheckBox.isSelected()) fasilitas = fasilitas.concat("Tissue");
            else fasilitas = fasilitas.concat("-");
            Penyewaan p = null;
            
            if (action == "Tambah") {
                p = new Penyewaan(lamaSewaInput.getText(), Float.parseFloat(totalHargaInput.getText()), fasilitas, kendaraan, customer);
                pControl.insertPenyewaan(p);
            }else if(action == "Edit"){
                p = new Penyewaan(selectedId, lamaSewaInput.getText(), Float.parseFloat(totalHargaInput.getText()), fasilitas, kendaraan, customer);
                pControl.updatePenyewaan(p);
            }
            clearText();
            showPenyewaan();
            setComponents(false);
            setEditDeleteBtn(false);
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Inputan Total Harga Harus Angka");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void snackCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snackCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snackCheckBoxActionPerformed

    private void tissueCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tissueCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tissueCheckBoxActionPerformed

    private void lamaSewaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaSewaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaSewaInputActionPerformed

    private void vehiclePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiclePanelMouseClicked
       KendaraanView kv = new KendaraanView();
       this.dispose();
       kv.setVisible(true);
    }//GEN-LAST:event_vehiclePanelMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(true);
        setComponents(false);
        try{
            TablePenyewaan penyewaan = pControl.showPenyewaan(searchInput.getText());
            if(penyewaan.getRowCount()==0){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan","Konfirmasi", JOptionPane.DEFAULT_OPTION);
                searchInput.setText("");
            }else{
                penyewaanTable.setModel(penyewaan);
            }
            clearText();
        }catch(Exception e){
            System.out.println("Error "+e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void kendaraanDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kendaraanDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kendaraanDropDownActionPerformed

    private void totalHargaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalHargaInputActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setComponents(true);
        action="Edit";
        searchInput.setText("");
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        searchInput.setText("");
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,
                "Apakah yakin ingin menghapus data?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        switch (getAnswer) {
            case 0:
                try {
                    pControl.deletePenyewaan(selectedId);
                    clearText();
                    showPenyewaan();
                    setComponents(false);
                    setEditDeleteBtn(false);
                    JOptionPane.showMessageDialog(null, " Data berhasil dihapus!");
                } catch (Exception e) {
                    System.out.println("Eror : " + e.getMessage());
                }
                break;
            case 1:
                //jika jawaban user adalah No
                break;  
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void penyewaanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penyewaanTableMouseClicked
        int indexKendaraan = -1;
        int indexCustomer = -1;
        setEditDeleteBtn(true);
        setComponents(false);
        cancelBtn.setEnabled(true);
        int clickedRow = penyewaanTable.getSelectedRow();
        TableModel tableModel = penyewaanTable.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow,8).toString());
        
        String merkKendaraan = tableModel.getValueAt(clickedRow,9).toString();
        for (Kendaraan kendaraan : listKendaraan) {
            if (kendaraan.getMerk().equals(merkKendaraan)) {
                indexKendaraan = listKendaraan.indexOf(kendaraan);
            }
        }
        kendaraanDropDown.setSelectedIndex(indexKendaraan);
        
        String namaCustomer = tableModel.getValueAt(clickedRow,10).toString();
        for (Customer customer: listCustomer) {
            if (customer.getNama().equals(namaCustomer)) {
                indexCustomer = listCustomer.indexOf(customer);
            }
        }
        namaDropDown.setSelectedIndex(indexCustomer);
        
        lamaSewaInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        totalHargaInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
        
        String fasilitasCheckBox = tableModel.getValueAt(clickedRow, 5).toString();
        if (fasilitasCheckBox.contains("Snack")) snackCheckBox.setSelected(true);
        else snackCheckBox.setSelected(false);
        
        if (fasilitasCheckBox.contains("Masker")) maskerCheckBox.setSelected(true);
        else maskerCheckBox.setSelected(false);
        
        if (fasilitasCheckBox.contains("Tissue")) tissueCheckBox.setSelected(true);
        else tissueCheckBox.setSelected(false);
        
    }//GEN-LAST:event_penyewaanTableMouseClicked

    private void exitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenyewaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenyewaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenyewaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenyewaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenyewaanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JLabel fasilitasLabel;
    private javax.swing.JLabel iconShutdown;
    private javax.swing.JPanel identityPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelompokLabel;
    private javax.swing.JComboBox<Kendaraan> kendaraanDropDown;
    private javax.swing.JLabel kendaraanLabel;
    private javax.swing.JTextField lamaSewaInput;
    private javax.swing.JLabel lamaSewaLabel;
    private javax.swing.JCheckBox maskerCheckBox;
    private javax.swing.JComboBox<Customer> namaDropDown;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel npm1;
    private javax.swing.JLabel npm2;
    private javax.swing.JTable penyewaanTable;
    private javax.swing.JLabel rentLabel;
    private javax.swing.JPanel rentPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JCheckBox snackCheckBox;
    private javax.swing.JCheckBox tissueCheckBox;
    private javax.swing.JTextField totalHargaInput;
    private javax.swing.JLabel totalHargaLabel;
    private javax.swing.JLabel vehicleLabel;
    private javax.swing.JPanel vehiclePanel;
    private javax.swing.JLabel viewLabel;
    // End of variables declaration//GEN-END:variables
}
